<<<<<<< HEAD
const sports = [
  {
    ques: "Where is the Wankhede Stadium located?",
    option1: "Delhi",
    option2: "Mumbai",
    option3: "Chennai",
    option4: "Kolkata",
    correct: "Mumbai",
  },
  {
    ques: "Who is the all-time leading goal scorer in international football?",
    option1: "Lionel Messi",
    option2: "Cristiano Ronaldo",
    option3: "Pelé",
    option4: "Zlatan Ibrahimović",
    correct: "Cristiano Ronaldo",
  },
  {
    ques: "In which sport would you perform a slam dunk?",
    option1: "Tennis",
    option2: "Basketball",
    option3: "Golf",
    option4: "Swimming",
    correct: "Basketball",
  },
  {
    ques: "Which country has won the most Olympic gold medals in total?",
    option1: "USA",
    option2: "China",
    option3: "Russia",
    option4: "Germany",
    correct: "USA",
  },
  {
    ques: "Who won the FIFA Ballon d'Or in 2020?",
    option1: "Lionel Messi",
    option2: "Cristiano Ronaldo",
    option3: "Robert Lewandowski",
    option4: "No Winner",
    correct: "Cancelled (No Winner)",
  },
  {
    ques: "Which city hosted the 2012 Summer Olympics?",
    option1: "Rio de Janeiro",
    option2: "Tokyo",
    option3: "London",
    option4: "Beijing",
    correct: "London",
  },
  {
    ques: "What is the scoring system called in tennis?",
    option1: "Points",
    option2: "Goals",
    option3: "Runs",
    option4: "Love",
    correct: "Love",
  },
  {
    ques: "Which country won the Cricket World Cup in 2019?",
    option1: "India",
    option2: "Australia",
    option3: "England",
    option4: "New Zealand",
    correct: "England",
  },
  {
    ques: "In which year did the first modern Olympic Games take place?",
    option1: "1886",
    option2: "1896",
    option3: "1906",
    option4: "1926",
    correct: "1896",
  },
  {
    ques: "Who won the Australian Open Men's Singles title in 2021?",
    option1: "Novak Djokovic",
    option2: "Rafael Nadal",
    option3: "Dominic Thiem",
    option4: "Roger Federer",
    correct: "Novak Djokovic",
  },
];

const space = [
  {
    ques: "What is the largest planet in our solar system?",
    option1: "Earth",
    option2: "Jupiter",
    option3: "Mars",
    option4: "Saturn",
    correct: "Jupiter",
  },
  {
    ques: "Which planet is known as the 'Red Planet'?",
    option1: "Venus",
    option2: "Mars",
    option3: "Jupiter",
    option4: "Saturn",
    correct: "Mars",
  },
  {
    ques: "What is the name of the closest galaxy to the Milky Way?",
    option1: "Andromeda",
    option2: "Triangulum",
    option3: "Messier 87",
    option4: "Centaurus A",
    correct: "Andromeda",
  },
  {
    ques: "How many moons does Earth have?",
    option1: "1",
    option2: "2",
    option3: "3",
    option4: "4",
    correct: "1",
  },
  {
    ques: "What is the name of the first artificial satellite launched into space?",
    option1: "Sputnik 1",
    option2: "Explorer 1",
    option3: "Vanguard 1",
    option4: "Hubble Space Telescope",
    correct: "Sputnik 1",
  },
  {
    ques: "Which planet is known as the 'Morning Star' or 'Evening Star'?",
    option1: "Venus",
    option2: "Mercury",
    option3: "Mars",
    option4: "Jupiter",
    correct: "Venus",
  },
  {
    ques: "What is the name of the largest moon of Saturn?",
    option1: "Titan",
    option2: "Enceladus",
    option3: "Rhea",
    option4: "Dione",
    correct: "Titan",
  },
  {
    ques: "Which space agency launched the Hubble Space Telescope?",
    option1: "NASA",
    option2: "ESA (European Space Agency)",
    option3: "ROSCOSMOS",
    option4: "ISRO",
    correct: "NASA",
  },
  {
    ques: "What is the name of the most famous comet that appears once in about 76 years?",
    option1: "Halley's Comet",
    option2: "Comet Hale-Bopp",
    option3: "Comet Neowise",
    option4: "Comet ISON",
    correct: "Halley's Comet",
  },
  {
    ques: "What is the largest moon of Neptune?",
    option1: "Triton",
    option2: "Nereid",
    option3: "Proteus",
    option4: "Larissa",
    correct: "Triton",
  },
];

const history = [
  {
    ques: "In which year did World War I begin?",
    option1: "1910",
    option2: "1914",
    option3: "1918",
    option4: "1922",
    correct: "1914",
  },
  {
    ques: "Who was the first President of the United States?",
    option1: "John Adams",
    option2: "George Washington",
    option3: "Thomas Jefferson",
    option4: "James Madison",
    correct: "George Washington",
  },
  {
    ques: "What ancient wonder was located in Alexandria, Egypt?",
    option1: "Hanging Gardens of Babylon",
    option2: "Colossus of Rhodes",
    option3: "Mausoleum at Halicarnassus",
    option4: "Lighthouse of Alexandria",
    correct: "Lighthouse of Alexandria",
  },
  {
    ques: "Who was the first woman to win a Nobel Prize?",
    option1: "Marie Curie",
    option2: "Mother Teresa",
    option3: "Rosalind Franklin",
    option4: "Ada Lovelace",
    correct: "Marie Curie",
  },
  {
    ques: "Which dynasty ruled ancient China from 221 BC to 206 BC?",
    option1: "Han",
    option2: "Qin",
    option3: "Tang",
    option4: "Ming",
    correct: "Qin",
  },
  {
    ques: "In which year did Christopher Columbus reach the Americas?",
    option1: "1492",
    option2: "1512",
    option3: "1556",
    option4: "1601",
    correct: "1492",
  },
  {
    ques: "Who wrote 'The Communist Manifesto'?",
    option1: "Karl Marx",
    option2: "Friedrich Engels",
    option3: "Vladimir Lenin",
    option4: "Mao Zedong",
    correct: "Karl Marx",
  },
  {
    ques: "What event marked the beginning of the French Revolution?",
    option1: "Storming of the Bastille",
    option2: "Battle of Waterloo",
    option3: "Execution of Louis XVI",
    option4: "Reign of Terror",
    correct: "Storming of the Bastille",
  },
  {
    ques: "Who was the leader of the Indian independence movement against British rule?",
    option1: "Mahatma Gandhi",
    option2: "Jawaharlal Nehru",
    option3: "Subhas Chandra Bose",
    option4: "Sardar Patel",
    correct: "Mahatma Gandhi",
  },
  {
    ques: "Which ancient civilization built the city of Machu Picchu?",
    option1: "Inca",
    option2: "Maya",
    option3: "Aztec",
    option4: "Egyptian",
    correct: "Inca",
  },
];
const reasoning = [
  {
    ques: "What comes next in the series: 2, 6, 12, 20, ___?",
    option1: "24",
    option2: "28",
    option3: "32",
    option4: "36",
    correct: "30",
  },
  {
    ques: "If CAT is coded as 312, how is DOG coded?",
    option1: "412",
    option2: "512",
    option3: "612",
    option4: "712",
    correct: "512",
  },
  {
    ques: "What is the missing number: 5, 12, __, 26, 35?",
    option1: "16",
    option2: "18",
    option3: "20",
    option4: "22",
    correct: "20",
  },
  {
    ques: "If RED is coded as 27, how is SEA coded?",
    option1: "41",
    option2: "44",
    option3: "47",
    option4: "50",
    correct: "44",
  },
  {
    ques: "Which figure is the odd one out?",
    option1: "Square",
    option2: "Circle",
    option3: "Triangle",
    option4: "Rectangle",
    correct: "Circle",
  },
  {
    ques: "If the day after tomorrow is a Sunday, what day is it today?",
    option1: "Monday",
    option2: "Tuesday",
    option3: "Wednesday",
    option4: "Thursday",
    correct: "Friday",
  },
  {
    ques: "What is the next letter in the series: A, C, E, G, ___?",
    option1: "H",
    option2: "I",
    option3: "F",
    option4: "J",
    correct: "I",
  },
  {
    ques: "If BOOK is coded as 25114, how is NOTE coded?",
    option1: "7145",
    option2: "8714",
    option3: "4517",
    option4: "5471",
    correct: "7145",
  },
  {
    ques: "What is the odd one out: Apple, Banana, Orange, Mango?",
    option1: "Banana",
    option2: "Orange",
    option3: "Mango",
    option4: "Apple",
    correct: "Apple",
  },
  {
    ques: "Complete the analogy: Sun is to Day as Moon is to ___?",
    option1: "Night",
    option2: "Darkness",
    option3: "Eclipse",
    option4: "Stars",
    correct: "Night",
  },
];

const current_Affairs = [
  {
    ques: "Who is the current Prime Minister of the United Kingdom?",
    option1: "Boris Johnson",
    option2: "Theresa May",
    option3: "David Cameron",
    option4: "Tony Blair",
    correct: "Boris Johnson",
  },
  {
    ques: "In which year did the COVID-19 pandemic begin?",
    option1: "2018",
    option2: "2019",
    option3: "2020",
    option4: "2021",
    correct: "2019",
  },
  {
    ques: "Which country recently hosted the G7 Summit?",
    option1: "USA",
    option2: "Germany",
    option3: "Canada",
    option4: "UK",
    correct: "UK",
  },
  {
    ques: "Who won the Nobel Peace Prize in 2020?",
    option1: "Malala Yousafzai",
    option2: "Greta Thunberg",
    option3: "World Food Programme",
    option4: "Abiy Ahmed",
    correct: "World Food Programme",
  },
  {
    ques: "Which country recently launched the Tianzhou-2 cargo spacecraft?",
    option1: "Russia",
    option2: "China",
    option3: "USA",
    option4: "India",
    correct: "China",
  },
  {
    ques: "What is the capital city of Afghanistan?",
    option1: "Kabul",
    option2: "Islamabad",
    option3: "Tehran",
    option4: "Baghdad",
    correct: "Kabul",
  },
  {
    ques: "Who is the current President of France?",
    option1: "Emmanuel Macron",
    option2: "François Hollande",
    option3: "Nicolas Sarkozy",
    option4: "Jacques Chirac",
    correct: "Emmanuel Macron",
  },
  {
    ques: "Which country recently signed the Abraham Accords?",
    option1: "Israel",
    option2: "Saudi Arabia",
    option3: "United Arab Emirates",
    option4: "Qatar",
    correct: "United Arab Emirates",
  },
  {
    ques: "What is the name of the recently discovered COVID-19 variant?",
    option1: "Delta",
    option2: "Gamma",
    option3: "Omicron",
    option4: "Beta",
    correct: "Omicron",
  },
  {
    ques: "Who won the 2021 Australian Open Women's Singles title?",
    option1: "Serena Williams",
    option2: "Simona Halep",
    option3: "Naomi Osaka",
    option4: "Ashleigh Barty",
    correct: "Naomi Osaka",
  },
];

const technology = [
  {
    ques: "Which company developed the first commercially available computer mouse?",
    option1: "IBM",
    option2: "Microsoft",
    option3: "Apple",
    option4: "Xerox",
    correct: "Xerox",
  },
  {
    ques: "What does the acronym 'HTML' stand for?",
    option1: "HyperText Markup Language",
    option2: "High-Level Textual Markup Language",
    option3: "HyperTransfer Markup Language",
    option4: "High-Level Transferable Markup Language",
    correct: "HyperText Markup Language",
  },
  {
    ques: "Who is the co-founder of Microsoft Corporation?",
    option1: "Bill Gates",
    option2: "Steve Jobs",
    option3: "Mark Zuckerberg",
    option4: "Elon Musk",
    correct: "Bill Gates",
  },
  {
    ques: "What is the programming language developed by Google?",
    option1: "Java",
    option2: "C#",
    option3: "Python",
    option4: "Go",
    correct: "Go",
  },
  {
    ques: "In computing, what does 'CPU' stand for?",
    option1: "Central Processing Unit",
    option2: "Computer Processing Unit",
    option3: "Central Processor Unit",
    option4: "Computer Processor Unit",
    correct: "Central Processing Unit",
  },
  {
    ques: "Which social media platform was launched by Mark Zuckerberg in 2004?",
    option1: "Twitter",
    option2: "Instagram",
    option3: "Facebook",
    option4: "LinkedIn",
    correct: "Facebook",
  },
  {
    ques: "What is the largest e-commerce company in the world?",
    option1: "Amazon",
    option2: "Alibaba",
    option3: "eBay",
    option4: "Walmart",
    correct: "Alibaba",
  },
  {
    ques: "Which programming language is often used for developing mobile applications?",
    option1: "Java",
    option2: "Swift",
    option3: "C++",
    option4: "Ruby",
    correct: "Swift",
  },
  {
    ques: "What is the purpose of a VPN (Virtual Private Network)?",
    option1: "Virus Protection Network",
    option2: "Virtual Personal Network",
    option3: "Virtual Private Network",
    option4: "Visual Processing Node",
    correct: "Virtual Private Network",
  },
  {
    ques: "Who is the CEO of Tesla Inc.?",
    option1: "Elon Musk",
    option2: "Jeff Bezos",
    option3: "Tim Cook",
    option4: "Satya Nadella",
    correct: "Elon Musk",
  },
];

export { sports, space, history, reasoning, current_Affairs, technology };
=======
const sports = [
  {
    ques: "Where is the Wankhede Stadium located?",
    option1: "Delhi",
    option2: "Mumbai",
    option3: "Chennai",
    option4: "Kolkata",
    correct: "Mumbai",
  },
  {
    ques: "Who is the all-time leading goal scorer in international football?",
    option1: "Lionel Messi",
    option2: "Cristiano Ronaldo",
    option3: "Pelé",
    option4: "Zlatan Ibrahimović",
    correct: "Cristiano Ronaldo",
  },
  {
    ques: "In which sport would you perform a slam dunk?",
    option1: "Tennis",
    option2: "Basketball",
    option3: "Golf",
    option4: "Swimming",
    correct: "Basketball",
  },
  {
    ques: "Which country has won the most Olympic gold medals in total?",
    option1: "USA",
    option2: "China",
    option3: "Russia",
    option4: "Germany",
    correct: "USA",
  },
  {
    ques: "Who won the FIFA Ballon d'Or in 2020?",
    option1: "Lionel Messi",
    option2: "Cristiano Ronaldo",
    option3: "Robert Lewandowski",
    option4: "No Winner",
    correct: "Cancelled (No Winner)",
  },
  {
    ques: "Which city hosted the 2012 Summer Olympics?",
    option1: "Rio de Janeiro",
    option2: "Tokyo",
    option3: "London",
    option4: "Beijing",
    correct: "London",
  },
  {
    ques: "What is the scoring system called in tennis?",
    option1: "Points",
    option2: "Goals",
    option3: "Runs",
    option4: "Love",
    correct: "Love",
  },
  {
    ques: "Which country won the Cricket World Cup in 2019?",
    option1: "India",
    option2: "Australia",
    option3: "England",
    option4: "New Zealand",
    correct: "England",
  },
  {
    ques: "In which year did the first modern Olympic Games take place?",
    option1: "1886",
    option2: "1896",
    option3: "1906",
    option4: "1926",
    correct: "1896",
  },
  {
    ques: "Who won the Australian Open Men's Singles title in 2021?",
    option1: "Novak Djokovic",
    option2: "Rafael Nadal",
    option3: "Dominic Thiem",
    option4: "Roger Federer",
    correct: "Novak Djokovic",
  },
];

const space = [
  {
    ques: "What is the largest planet in our solar system?",
    option1: "Earth",
    option2: "Jupiter",
    option3: "Mars",
    option4: "Saturn",
    correct: "Jupiter",
  },
  {
    ques: "Which planet is known as the 'Red Planet'?",
    option1: "Venus",
    option2: "Mars",
    option3: "Jupiter",
    option4: "Saturn",
    correct: "Mars",
  },
  {
    ques: "What is the name of the closest galaxy to the Milky Way?",
    option1: "Andromeda",
    option2: "Triangulum",
    option3: "Messier 87",
    option4: "Centaurus A",
    correct: "Andromeda",
  },
  {
    ques: "How many moons does Earth have?",
    option1: "1",
    option2: "2",
    option3: "3",
    option4: "4",
    correct: "1",
  },
  {
    ques: "What is the name of the first artificial satellite launched into space?",
    option1: "Sputnik 1",
    option2: "Explorer 1",
    option3: "Vanguard 1",
    option4: "Hubble Space Telescope",
    correct: "Sputnik 1",
  },
  {
    ques: "Which planet is known as the 'Morning Star' or 'Evening Star'?",
    option1: "Venus",
    option2: "Mercury",
    option3: "Mars",
    option4: "Jupiter",
    correct: "Venus",
  },
  {
    ques: "What is the name of the largest moon of Saturn?",
    option1: "Titan",
    option2: "Enceladus",
    option3: "Rhea",
    option4: "Dione",
    correct: "Titan",
  },
  {
    ques: "Which space agency launched the Hubble Space Telescope?",
    option1: "NASA",
    option2: "ESA (European Space Agency)",
    option3: "ROSCOSMOS",
    option4: "ISRO",
    correct: "NASA",
  },
  {
    ques: "What is the name of the most famous comet that appears once in about 76 years?",
    option1: "Halley's Comet",
    option2: "Comet Hale-Bopp",
    option3: "Comet Neowise",
    option4: "Comet ISON",
    correct: "Halley's Comet",
  },
  {
    ques: "What is the largest moon of Neptune?",
    option1: "Triton",
    option2: "Nereid",
    option3: "Proteus",
    option4: "Larissa",
    correct: "Triton",
  },
];

const history = [
  {
    ques: "In which year did World War I begin?",
    option1: "1910",
    option2: "1914",
    option3: "1918",
    option4: "1922",
    correct: "1914",
  },
  {
    ques: "Who was the first President of the United States?",
    option1: "John Adams",
    option2: "George Washington",
    option3: "Thomas Jefferson",
    option4: "James Madison",
    correct: "George Washington",
  },
  {
    ques: "What ancient wonder was located in Alexandria, Egypt?",
    option1: "Hanging Gardens of Babylon",
    option2: "Colossus of Rhodes",
    option3: "Mausoleum at Halicarnassus",
    option4: "Lighthouse of Alexandria",
    correct: "Lighthouse of Alexandria",
  },
  {
    ques: "Who was the first woman to win a Nobel Prize?",
    option1: "Marie Curie",
    option2: "Mother Teresa",
    option3: "Rosalind Franklin",
    option4: "Ada Lovelace",
    correct: "Marie Curie",
  },
  {
    ques: "Which dynasty ruled ancient China from 221 BC to 206 BC?",
    option1: "Han",
    option2: "Qin",
    option3: "Tang",
    option4: "Ming",
    correct: "Qin",
  },
  {
    ques: "In which year did Christopher Columbus reach the Americas?",
    option1: "1492",
    option2: "1512",
    option3: "1556",
    option4: "1601",
    correct: "1492",
  },
  {
    ques: "Who wrote 'The Communist Manifesto'?",
    option1: "Karl Marx",
    option2: "Friedrich Engels",
    option3: "Vladimir Lenin",
    option4: "Mao Zedong",
    correct: "Karl Marx",
  },
  {
    ques: "What event marked the beginning of the French Revolution?",
    option1: "Storming of the Bastille",
    option2: "Battle of Waterloo",
    option3: "Execution of Louis XVI",
    option4: "Reign of Terror",
    correct: "Storming of the Bastille",
  },
  {
    ques: "Who was the leader of the Indian independence movement against British rule?",
    option1: "Mahatma Gandhi",
    option2: "Jawaharlal Nehru",
    option3: "Subhas Chandra Bose",
    option4: "Sardar Patel",
    correct: "Mahatma Gandhi",
  },
  {
    ques: "Which ancient civilization built the city of Machu Picchu?",
    option1: "Inca",
    option2: "Maya",
    option3: "Aztec",
    option4: "Egyptian",
    correct: "Inca",
  },
];
const reasoning = [
  {
    ques: "What comes next in the series: 2, 6, 12, 20, ___?",
    option1: "24",
    option2: "28",
    option3: "32",
    option4: "36",
    correct: "30",
  },
  {
    ques: "If CAT is coded as 312, how is DOG coded?",
    option1: "412",
    option2: "512",
    option3: "612",
    option4: "712",
    correct: "512",
  },
  {
    ques: "What is the missing number: 5, 12, __, 26, 35?",
    option1: "16",
    option2: "18",
    option3: "20",
    option4: "22",
    correct: "20",
  },
  {
    ques: "If RED is coded as 27, how is SEA coded?",
    option1: "41",
    option2: "44",
    option3: "47",
    option4: "50",
    correct: "44",
  },
  {
    ques: "Which figure is the odd one out?",
    option1: "Square",
    option2: "Circle",
    option3: "Triangle",
    option4: "Rectangle",
    correct: "Circle",
  },
  {
    ques: "If the day after tomorrow is a Sunday, what day is it today?",
    option1: "Monday",
    option2: "Tuesday",
    option3: "Wednesday",
    option4: "Thursday",
    correct: "Friday",
  },
  {
    ques: "What is the next letter in the series: A, C, E, G, ___?",
    option1: "H",
    option2: "I",
    option3: "F",
    option4: "J",
    correct: "I",
  },
  {
    ques: "If BOOK is coded as 25114, how is NOTE coded?",
    option1: "7145",
    option2: "8714",
    option3: "4517",
    option4: "5471",
    correct: "7145",
  },
  {
    ques: "What is the odd one out: Apple, Banana, Orange, Mango?",
    option1: "Banana",
    option2: "Orange",
    option3: "Mango",
    option4: "Apple",
    correct: "Apple",
  },
  {
    ques: "Complete the analogy: Sun is to Day as Moon is to ___?",
    option1: "Night",
    option2: "Darkness",
    option3: "Eclipse",
    option4: "Stars",
    correct: "Night",
  },
];

const current_Affairs = [
  {
    ques: "Who is the current Prime Minister of the United Kingdom?",
    option1: "Boris Johnson",
    option2: "Theresa May",
    option3: "David Cameron",
    option4: "Tony Blair",
    correct: "Boris Johnson",
  },
  {
    ques: "In which year did the COVID-19 pandemic begin?",
    option1: "2018",
    option2: "2019",
    option3: "2020",
    option4: "2021",
    correct: "2019",
  },
  {
    ques: "Which country recently hosted the G7 Summit?",
    option1: "USA",
    option2: "Germany",
    option3: "Canada",
    option4: "UK",
    correct: "UK",
  },
  {
    ques: "Who won the Nobel Peace Prize in 2020?",
    option1: "Malala Yousafzai",
    option2: "Greta Thunberg",
    option3: "World Food Programme",
    option4: "Abiy Ahmed",
    correct: "World Food Programme",
  },
  {
    ques: "Which country recently launched the Tianzhou-2 cargo spacecraft?",
    option1: "Russia",
    option2: "China",
    option3: "USA",
    option4: "India",
    correct: "China",
  },
  {
    ques: "What is the capital city of Afghanistan?",
    option1: "Kabul",
    option2: "Islamabad",
    option3: "Tehran",
    option4: "Baghdad",
    correct: "Kabul",
  },
  {
    ques: "Who is the current President of France?",
    option1: "Emmanuel Macron",
    option2: "François Hollande",
    option3: "Nicolas Sarkozy",
    option4: "Jacques Chirac",
    correct: "Emmanuel Macron",
  },
  {
    ques: "Which country recently signed the Abraham Accords?",
    option1: "Israel",
    option2: "Saudi Arabia",
    option3: "United Arab Emirates",
    option4: "Qatar",
    correct: "United Arab Emirates",
  },
  {
    ques: "What is the name of the recently discovered COVID-19 variant?",
    option1: "Delta",
    option2: "Gamma",
    option3: "Omicron",
    option4: "Beta",
    correct: "Omicron",
  },
  {
    ques: "Who won the 2021 Australian Open Women's Singles title?",
    option1: "Serena Williams",
    option2: "Simona Halep",
    option3: "Naomi Osaka",
    option4: "Ashleigh Barty",
    correct: "Naomi Osaka",
  },
];

const technology = [
  {
    ques: "Which company developed the first commercially available computer mouse?",
    option1: "IBM",
    option2: "Microsoft",
    option3: "Apple",
    option4: "Xerox",
    correct: "Xerox",
  },
  {
    ques: "What does the acronym 'HTML' stand for?",
    option1: "HyperText Markup Language",
    option2: "High-Level Textual Markup Language",
    option3: "HyperTransfer Markup Language",
    option4: "High-Level Transferable Markup Language",
    correct: "HyperText Markup Language",
  },
  {
    ques: "Who is the co-founder of Microsoft Corporation?",
    option1: "Bill Gates",
    option2: "Steve Jobs",
    option3: "Mark Zuckerberg",
    option4: "Elon Musk",
    correct: "Bill Gates",
  },
  {
    ques: "What is the programming language developed by Google?",
    option1: "Java",
    option2: "C#",
    option3: "Python",
    option4: "Go",
    correct: "Go",
  },
  {
    ques: "In computing, what does 'CPU' stand for?",
    option1: "Central Processing Unit",
    option2: "Computer Processing Unit",
    option3: "Central Processor Unit",
    option4: "Computer Processor Unit",
    correct: "Central Processing Unit",
  },
  {
    ques: "Which social media platform was launched by Mark Zuckerberg in 2004?",
    option1: "Twitter",
    option2: "Instagram",
    option3: "Facebook",
    option4: "LinkedIn",
    correct: "Facebook",
  },
  {
    ques: "What is the largest e-commerce company in the world?",
    option1: "Amazon",
    option2: "Alibaba",
    option3: "eBay",
    option4: "Walmart",
    correct: "Alibaba",
  },
  {
    ques: "Which programming language is often used for developing mobile applications?",
    option1: "Java",
    option2: "Swift",
    option3: "C++",
    option4: "Ruby",
    correct: "Swift",
  },
  {
    ques: "What is the purpose of a VPN (Virtual Private Network)?",
    option1: "Virus Protection Network",
    option2: "Virtual Personal Network",
    option3: "Virtual Private Network",
    option4: "Visual Processing Node",
    correct: "Virtual Private Network",
  },
  {
    ques: "Who is the CEO of Tesla Inc.?",
    option1: "Elon Musk",
    option2: "Jeff Bezos",
    option3: "Tim Cook",
    option4: "Satya Nadella",
    correct: "Elon Musk",
  },
];

export { sports, space, history, reasoning, current_Affairs, technology };
>>>>>>> fd8079f5db48911cf9ce54c2b787b85b19833b2e
